apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: research-env-exf-final2
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest





